### ISSUE TITLE
Add alt text to images

### ISSUE THREAD

**Issue by AhamSammich** [AhamSammich/lets-play-koikoi#34]
Increase accessibility by adding alt text to the card images.

**Comment by Peacesandy** [comment]
Hi  Aham Sammich i'll like on the issue by adding alt text to the card images

**Comment by Peacesandy** [comment]
I'll like to contribute to this project, how do i go about it

**Comment by AhamSammich** [comment]
Hi @Peacesandy! Thank you for your interest! I'm still new to collaborating via GitHub, but here are some steps to get started: 

1. Fork the repository on GitHub by clicking the "Fork" button in the upper-right corner of the repository page.
2. Clone your fork to your local machine using Git.
3. Install the necessary dependencies by running `npm install`.

I'll be sure to update my README and add a CONTRIBUTING.md with more info. I apologize in advance if I'm slow to respond, but please let me know if you have any questions.
